openapi: "3.0.0"
info:
  version: 1.0.0
  title: FHIR-R4-Slot-UKCore-Component
paths: {}
components: 
  schemas:
    Extension-UKCore-DeliveryChannel:
      allOf:
        - $ref: '/exchange_modules/911613bd-dcc3-46b1-8fe6-805375fe7d85/fhir-r4-common-components/1.0.5/fhir-r4-common-components.yaml#/components/schemas/Element'      
      type: object
      description: >
        This describes the delivery channel of a scheduled appointment.         
      properties:
        url: 
            type: string
            enum:
              - https://fhir.hl7.org.uk/StructureDefinition/Extension-UKCore-DeliveryChannel
        valueCodeableConcept: 
            allOf:
              - $ref: 'exchange_modules/911613bd-dcc3-46b1-8fe6-805375fe7d85/fhir-r4-common-components/1.0.5/fhir-r4-common-components.yaml#/components/schemas/CodeableConcept'
            properties:
              coding:
                type: array
                items:
                  oneOf:
                    - $ref: '#/components/schemas/ValueSetUKCoreDeliveryChannel'
                    - $ref: 'exchange_modules/911613bd-dcc3-46b1-8fe6-805375fe7d85/fhir-r4-common-components/1.0.5/fhir-r4-common-components.yaml#/components/schemas/Coding'

    ValueSetUKCoreDeliveryChannel:
       # UK Core Delivery Channel
      type: object
      allOf:
        - $ref: 'exchange_modules/911613bd-dcc3-46b1-8fe6-805375fe7d85/fhir-r4-common-components/1.0.5/fhir-r4-common-components.yaml#/components/schemas/Coding'
        - type: object
      properties:
        system:
          type: string
          enum:             
            - https://fhir.hl7.org.uk/CodeSystem/UKCore-DeliveryChannel
        code:
          type: string
          enum: ["In-person", "Telephone", "Video"]

    ValueSetUKCorePracticeSettingCode:
       # UK Core Delivery Channel
      type: object
      allOf:
        - $ref: 'exchange_modules/911613bd-dcc3-46b1-8fe6-805375fe7d85/fhir-r4-common-components/1.0.5/fhir-r4-common-components.yaml#/components/schemas/Coding'
        - type: object
      properties:
        system:
          type: string
          enum:             
            - https://fhir.hl7.org.uk/CodeSystem/UKCore-PracticeSettingCode
        code:
          type: string
          enum: ["100", "101", "107", "110", "120", "130", "140", "141", "142", "143", "145", "146", "147", "148", "149", "150", "160", "170", "171", "180", "190", "192", "200", "300", "301", "302", "303", "304", "305", "310", "311", "313", "314", "315", "317", "320", "321", "325", "326", "330", "340", "350", "352", "360", "361", "370", "371", "400", "401", "410", "420", "421", "430", "450", "451", "460", "500", "501", "502", "504", "560", "600", "601", "700", "710", "711", "712", "713", "715", "800", "810", "820", "821", "822", "823", "824", "830", "831", "833", "834", "900", "901", "902", "903", "904", "950", "960"]

    Slot:
      allOf:  
          - $ref: '/exchange_modules/911613bd-dcc3-46b1-8fe6-805375fe7d85/fhir-r4-common-components/1.0.5/fhir-r4-common-components.yaml#/components/schemas/DomainResource'      
          - $ref: '/components/schemas/slot-base.yaml#/components/schemas/Slot'
      type: object
      properties:
        extension:
          description: Additional Content defined by implementations
          type: array
          items:            
             $ref: '#/components/schemas/Extension-UKCore-DeliveryChannel'
        specialty:
          description: Specific type of specialty
          type: array
          items:
            allOf:
              - $ref: 'exchange_modules/911613bd-dcc3-46b1-8fe6-805375fe7d85/fhir-r4-common-components/1.0.5/fhir-r4-common-components.yaml#/components/schemas/CodeableConcept'
            type: object
            properties:
              coding:
                type: array
                items:                  
                  oneOf:
                    - $ref: '#/components/schemas/ValueSetUKCorePracticeSettingCode'
                    - $ref: 'exchange_modules/911613bd-dcc3-46b1-8fe6-805375fe7d85/fhir-r4-common-components/1.0.5/fhir-r4-common-components.yaml#/components/schemas/Coding'

    SlotEntry:     
      allOf:
        - $ref: '/exchange_modules/911613bd-dcc3-46b1-8fe6-805375fe7d85/fhir-r4-common-components/1.0.5/fhir-r4-common-components.yaml#/components/schemas/Entry'
      type: object
      properties:
        resource:
          $ref: '#/components/schemas/Slot'

    SlotBundle:
      allOf:
        - $ref: '/exchange_modules/911613bd-dcc3-46b1-8fe6-805375fe7d85/fhir-r4-common-components/1.0.5/fhir-r4-common-components.yaml#/components/schemas/Resource'
      type: object
      description: >
        Contains a collection of resources
        + Rule: total only when a search or history
        + Rule: entry.search only when a search
        + Rule: entry.request mandatory for batch/transaction/history, otherwise prohibited
        + Rule: entry.response mandatory for batch-response/transaction-response/history, otherwise prohibited
        + Rule: FullUrl must be unique in a bundle, or else entries with the same fullUrl must have different meta.versionId (except in history bundles)
        + Rule: A document must have an identifier with a system and a value
        + Rule: A document must have a date
        + Rule: A document must have a Composition as the first resource
        + Rule: A message must have a MessageHeader as the first resource
        Elements defined in Ancestors: id, meta, implicitRules, language
      properties:             
        resourceType:
          type: string
          enum: [Bundle]
        identifier:
          $ref: '/exchange_modules/911613bd-dcc3-46b1-8fe6-805375fe7d85/fhir-r4-common-components/1.0.5/fhir-r4-common-components.yaml#/components/schemas/Identifier'
          description: Persistent identifier for the bundle
        type:
          $ref: '/exchange_modules/911613bd-dcc3-46b1-8fe6-805375fe7d85/fhir-r4-common-components/1.0.5/fhir-r4-common-components.yaml#/components/schemas/code'
          description: document | message | transaction | transaction-response | batch | batch-response | history | searchset | collection
          enum: [document, message, transaction, transaction-response, batch, batch-response, history, searchset, collection]
        timestamp:
          $ref: '/exchange_modules/911613bd-dcc3-46b1-8fe6-805375fe7d85/fhir-r4-common-components/1.0.5/fhir-r4-common-components.yaml#/components/schemas/instant'
          description: When the bundle was assembled
        total:
          $ref: '/exchange_modules/911613bd-dcc3-46b1-8fe6-805375fe7d85/fhir-r4-common-components/1.0.5/fhir-r4-common-components.yaml#/components/schemas/unsignedInt'
          description: If search, the total number of matches
        link:
          description: Links related to this Bundle
          type: array
          items:
            allOf:
              - $ref: '/exchange_modules/911613bd-dcc3-46b1-8fe6-805375fe7d85/fhir-r4-common-components/1.0.5/fhir-r4-common-components.yaml#/components/schemas/BackboneElement'
            type: object
            properties:
              relation:
                type: string
                description: See http://www.iana.org/assignments/link-relations/link-relations.xhtml#link-relations-1
              url:
                $ref: '/exchange_modules/911613bd-dcc3-46b1-8fe6-805375fe7d85/fhir-r4-common-components/1.0.5/fhir-r4-common-components.yaml#/components/schemas/uri'
                description: Reference details for the link
            required:
              - relation
              - url
        entry:
          description: |
            Entry in the bundle - will have a resource or information
            + Rule: must be a resource unless there's a request or response
            + Rule: fullUrl cannot be a version specific reference
            This repeating element order: For bundles of type 'document' and 'message', the first resource is special (must be Composition or MessageHeader respectively). For all bundles, the meaning of the order of entries depends on the bundle type
          type: array
          items:
            $ref: '#/components/schemas/SlotEntry'
        signature:
          $ref: '/exchange_modules/911613bd-dcc3-46b1-8fe6-805375fe7d85/fhir-r4-common-components/1.0.5/fhir-r4-common-components.yaml#/components/schemas/Signature'
          description: Digital Signature              
      required:
        - type
        - resourceType


